function [explain] = pca_plot(X,...
    components,...
    L_relevant,...
    f,...
    tt)
%PCA_PLOT Summary of this function goes here
%   Detailed explanation goes here

[~, ~, explain, Y, ~] = pca_fun(X', components);

figure(f);
set(gcf, "Position", [100, 100, 1200, 800]);

t = tiledlayout(3, 5,...
    "TileSpacing", "Compact",...
    "Padding", "Compact");

for i = 1:components
    for j = i+1:components
        nexttile;
        scatter(Y(i, :), Y(j, :),...
            10, L_relevant, "filled");
        title(sprintf("PC %d vs PC %d",...
            i, j));
        ax = gca;
        ax.XTick = [];
        ax.YTick = [];
        box on;
        ax.LineWidth = 1.5;
    end
end
title(t, tt, ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');